[book]
authors = ["Mutsuha Asada"]
language = "ja"
src = "src"
title = "note.momee.mt"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js"]

